feat: adding jest config for typescript :rocket:
colantuomo/discord-bot pull request #38
Opened 2020-12-15 03:54 UTC by colantuomo

Adding `jest` config for future tests.

2020-12-15 14:44 UTC, DenisSlapelis requested changes

2020-12-15 14:44 UTC, DenisSlapelis commented on .github/workflows/node.js.yml
> +        branches: [master]
Teoricamente nao fazemos push na master, então sugiro deixar apenas "on: push" para buildar independente da branch, ou remover o build no push e deixar apenas no pull request

2020-12-15 14:44 UTC, DenisSlapelis commented on .github/workflows/node.js.yml
> +                node-version: [12.x]
Atualmente só estamos utilizando a versão 12, e nao acho que utilizaremos multiplas versoes simultaneamente futuramente, então acho que essa matrix poderia ser removida e a versao adicionada no node-version do step mesmo

2020-12-15 14:44 UTC, DenisSlapelis commented on jest.config.ts
> +  // cacheDirectory: "C:\\Users\\Paulo\\AppData\\Local\\Temp\\jest",
E esse diretório aqui?

2020-12-16 17:49 UTC, colantuomo commented on .github/workflows/node.js.yml
> +        branches: [master]
mas esse push ai não significa os PR's abertos para mergear na master? (tipo esse aqui)

2020-12-16 17:50 UTC, colantuomo commented on .github/workflows/node.js.yml
> +                node-version: [12.x]
é só remover o matrix e deixar `node-version` ?

2020-12-16 17:51 UTC, colantuomo commented on jest.config.ts
> +  // cacheDirectory: "C:\\Users\\Paulo\\AppData\\Local\\Temp\\jest",
essa msg foi gerada junto com o `CLI` do jest quando eu gerei o arquivo. Não sei pra que serve (mas ta comentada tb ai men)

2020-12-16 17:52 UTC, DenisSlapelis commented on .github/workflows/node.js.yml
> +        branches: [master]
Não, o push ele vai ficar observando os push na(s) branch(es) selecionada(s). O de quando abre PR é o _pull_request_ que voce colocou ali

2020-12-16 17:54 UTC, DenisSlapelis commented on .github/workflows/node.js.yml
> +                node-version: [12.x]
Sim, pode tirar todo esse strategy na verdade

2020-12-16 17:54 UTC, colantuomo commented on .github/workflows/node.js.yml
> +        branches: [master]
Beleza, se quiser pode alterar na branch ai

2020-12-16 17:55 UTC, DenisSlapelis commented on jest.config.ts
> +  // cacheDirectory: "C:\\Users\\Paulo\\AppData\\Local\\Temp\\jest",
MAS E O PROFISSIONALISMO??? FICA A PASTA DA SUA MAQUINA AQUI NO PROJETO PARCEIRO

2020-12-16 17:57 UTC, colantuomo commented on jest.config.ts
> +  // cacheDirectory: "C:\\Users\\Paulo\\AppData\\Local\\Temp\\jest",
Só remover ai filho de

2020-12-16 17:58 UTC, colantuomo commented on .github/workflows/node.js.yml
> +                node-version: [12.x]
```suggestion
```

2020-12-17 17:31 UTC, DenisSlapelis approved these changes

2020-12-17 17:42 UTC, closed without merging